<?php

return array (
  'version' => '6.2.2',
  'title' => 'Social Editors',
  'type' => 'fact-sheet',
  'id' => '64b7f81414816d',
  'updated' => 1691463188,
  'columns' =>
  array (
    'title' =>
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '326',
      'width_unit' => 'px',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'off',
      'search' => 'on',
      'name' => 'title',
    ),
    '64c9b76413f7d0' =>
    array (
      'type' => 'column-Parent_Post_Column',
      'label' => 'Parent Post',
      'width' => '190',
      'width_unit' => 'px',
      'export' => 'on',
      'filter' => 'on',
      'filter_label' => 'All Posts',
      'name' => '64c9b76413f7d0',
    ),
    'date' =>
    array (
      'type' => 'date',
      'label' => 'Date',
      'width' => '202',
      'width_unit' => 'px',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'off',
      'search' => 'on',
      'filter' => 'on',
      'filter_label' => '',
      'filter_format' => 'range',
      'name' => 'date',
    ),
    '64d1adfe37ced8' =>
    array (
      'type' => 'column-author_name',
      'label' => 'Author',
      'width' => '',
      'width_unit' => '%',
      'display_author_as' => 'display_name',
      'user_link_to' => 'edit_user',
      'export' => 'on',
      'edit' => 'off',
      'bulk_edit' => 'off',
      'filter' => 'on',
      'filter_label' => '',
      'name' => '64d1adfe37ced8',
    ),
    'wpseo-score' =>
    array (
      'type' => 'wpseo-score',
      'label' => '<span class="yoast-column-seo-score yoast-column-header-has-tooltip" data-tooltip-text="SEO score"><span class="screen-reader-text">SEO score</span></span></span>',
      'width' => '52',
      'width_unit' => 'px',
      'export' => 'on',
      'sort' => 'on',
      'name' => 'wpseo-score',
    ),
    'wpseo-score-readability' =>
    array (
      'type' => 'wpseo-score-readability',
      'label' => '<span class="yoast-column-readability yoast-column-header-has-tooltip" data-tooltip-text="Readability score"><span class="screen-reader-text">Readability score</span></span></span>',
      'width' => '50',
      'width_unit' => 'px',
      'export' => 'on',
      'sort' => 'on',
      'name' => 'wpseo-score-readability',
    ),
    'wpseo-links' =>
    array (
      'type' => 'wpseo-links',
      'label' => '<span class="yoast-linked-to yoast-column-header-has-tooltip"><span class="screen-reader-text">Outgoing internal links</span></span>',
      'width' => '50',
      'width_unit' => 'px',
      'sort' => 'on',
      'name' => 'wpseo-links',
    ),
    'wpseo-cornerstone' =>
    array (
      'type' => 'wpseo-cornerstone',
      'label' => '<span class="yoast-column-cornerstone yoast-column-header-has-tooltip" data-tooltip-text="Is this cornerstone content?"><span class="screen-reader-text">Cornerstone content</span></span>',
      'width' => '50',
      'width_unit' => 'px',
      'export' => 'on',
      'sort' => 'on',
      'name' => 'wpseo-cornerstone',
    ),
    'wpseo-title' =>
    array (
      'type' => 'wpseo-title',
      'label' => 'SEO Title',
      'width' => '226',
      'width_unit' => 'px',
      'export' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'wpseo-title',
    ),
    'wpseo-metadesc' =>
    array (
      'type' => 'wpseo-metadesc',
      'label' => 'Meta Desc.',
      'width' => '238',
      'width_unit' => 'px',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'wpseo-metadesc',
    ),
    'wpseo-focuskw' =>
    array (
      'type' => 'wpseo-focuskw',
      'label' => 'Keyphrase',
      'width' => '239',
      'width_unit' => 'px',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'name' => 'wpseo-focuskw',
    ),
    '64b7f86793f7d0' =>
    array (
      'type' => 'column-yoast_facebook_description',
      'label' => 'Facebook Description',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => '64b7f86793f7d0',
    ),
    '64b7f8704e147c' =>
    array (
      'type' => 'column-yoast_twitter_description',
      'label' => 'Twitter Description',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => '64b7f8704e147c',
    ),
    '64b7f87fd1eb84' =>
    array (
      'type' => 'column-yoast_facebook_image',
      'label' => 'Facebook Image',
      'width' => '',
      'width_unit' => '%',
      'image_size' => 'thumbnail',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => '64b7f87fd1eb84',
    ),
    '64b7f8913c6a80' =>
    array (
      'type' => 'column-yoast_twitter_image',
      'label' => 'Twitter Image',
      'width' => '',
      'width_unit' => '%',
      'image_size' => 'thumbnail',
      'image_size_w' => '60',
      'image_size_h' => '60',
      'export' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => '64b7f8913c6a80',
    ),
  ),
  'settings' =>
  array (
    'roles' =>
    array (
    ),
    'users' =>
    array (
    ),
    'sorting' => '0',
    'sorting_order' => 'asc',
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_bulk_delete' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_conditional_formatting' => 'off',
    'hide_new_inline' => 'on',
    'resize_columns' => 'off',
    'column_order' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_filter_category' => 'off',
    'hide_filter_post_format' => 'off',
    'hide_filter_yoast_seo_scores' => 'off',
    'hide_filter_yoast_readability_score' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'hide_row_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'primary_column' => '',
    'filter_segment' => '',
  ),
);
