<?php

return array (
  'version' => '6.4.10',
  'list_screen' => 
  array (
    'title' => 'Default View',
    'type' => 'post',
    'id' => '64b7f74da526c',
    'updated' => 1723742833,
    'columns' => 
    array (
      'title' => 
      array (
        'type' => 'title',
        'label' => 'Title',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'title',
      ),
      'date' => 
      array (
        'type' => 'date',
        'label' => 'Date',
        'width' => '',
        'width_unit' => '%',
        'filter' => 'on',
        'filter_label' => '',
        'filter_format' => 'range',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'name' => 'date',
      ),
      '64d1ade4fb22d0' => 
      array (
        'type' => 'column-author_name',
        'label' => 'Author',
        'width' => '',
        'width_unit' => '%',
        'display_author_as' => 'display_name',
        'user_link_to' => 'edit_user',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => '64d1ade4fb22d0',
      ),
      'categories' => 
      array (
        'type' => 'categories',
        'label' => 'Topics',
        'width' => '15',
        'width_unit' => '%',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => 'categories',
      ),
      'taxonomy-bylines' => 
      array (
        'type' => 'taxonomy-bylines',
        'label' => 'Bylines',
        'width' => '',
        'width_unit' => '%',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => 'taxonomy-bylines',
      ),
      'taxonomy-formats' => 
      array (
        'type' => 'taxonomy-formats',
        'label' => 'Formats',
        'width' => '',
        'width_unit' => '%',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => 'taxonomy-formats',
      ),
      'taxonomy-regions-countries' => 
      array (
        'type' => 'taxonomy-regions-countries',
        'label' => 'Regions & Countries',
        'width' => '',
        'width_unit' => '%',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => 'taxonomy-regions-countries',
      ),
      'taxonomy-research-teams' => 
      array (
        'type' => 'taxonomy-research-teams',
        'label' => 'Research Teams',
        'width' => '',
        'width_unit' => '%',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => 'taxonomy-research-teams',
      ),
      '64c9bb5bc4dd30' => 
      array (
        'type' => 'column-PRC_ATTACHMENTS_COLUMN',
        'label' => 'Attachments',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'name' => '64c9bb5bc4dd30',
      ),
      '64c9bb6a50a3d8' => 
      array (
        'type' => 'column-Parent_Post_Column',
        'label' => 'Parent Post',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'name' => '64c9bb6a50a3d8',
      ),
      '482b94d6cc0830' => 
      array (
        'type' => 'column-meta',
        'label' => 'Display Bylines?',
        'width' => '',
        'width_unit' => '%',
        'field' => 'displayBylines',
        'field_type' => 'checkmark',
        'before' => '',
        'after' => '',
        'edit' => 'on',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => '482b94d6cc0830',
      ),
      '1cf42c6f960419' => 
      array (
        'type' => 'column-date_published',
        'label' => 'Date Published',
        'width' => '',
        'width_unit' => '%',
        'date_format' => 'wp_default',
        'filter' => 'off',
        'filter_label' => '',
        'filter_format' => '',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'name' => '1cf42c6f960419',
      ),
    ),
    'settings' => 
    array (
      'roles' => 
      array (
      ),
      'users' => 
      array (
      ),
      'sorting' => '0',
      'sorting_order' => 'asc',
      'hide_inline_edit' => 'off',
      'hide_bulk_edit' => 'off',
      'hide_bulk_delete' => 'off',
      'hide_smart_filters' => 'off',
      'hide_segments' => 'off',
      'hide_export' => 'off',
      'hide_conditional_formatting' => 'off',
      'hide_new_inline' => 'on',
      'resize_columns' => 'off',
      'column_order' => 'off',
      'hide_filters' => 'off',
      'hide_filter_post_date' => 'off',
      'hide_filter_category' => 'off',
      'hide_filter_post_format' => 'off',
      'hide_filter_yoast_seo_scores' => 'off',
      'hide_filter_yoast_readability_score' => 'off',
      'hide_submenu' => 'off',
      'hide_search' => 'off',
      'hide_bulk_actions' => 'off',
      'hide_row_actions' => 'off',
      'horizontal_scrolling' => 'off',
      'primary_column' => '',
      'filter_segment' => '',
      'wrapping' => 'wrap',
    ),
  ),
);