<?php

return array (
  'version' => '6.4.10',
  'list_screen' => 
  array (
    'title' => '',
    'type' => 'fact-sheet',
    'id' => '64b7f74da527d',
    'updated' => 1723742816,
    'columns' => 
    array (
      'title' => 
      array (
        'type' => 'title',
        'label' => 'Title',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'title',
      ),
      'date' => 
      array (
        'type' => 'date',
        'label' => 'Date',
        'width' => '',
        'width_unit' => '%',
        'filter' => 'on',
        'filter_label' => '',
        'filter_format' => 'range',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'name' => 'date',
      ),
      '64d1ade4fb22d0' => 
      array (
        'type' => 'column-author_name',
        'label' => 'Author',
        'width' => '',
        'width_unit' => '%',
        'display_author_as' => 'display_name',
        'user_link_to' => 'edit_user',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => '64d1ade4fb22d0',
      ),
      'categories' => 
      array (
        'type' => 'categories',
        'label' => 'Topics',
        'width' => '15',
        'width_unit' => '%',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => 'categories',
      ),
      'taxonomy-bylines' => 
      array (
        'type' => 'taxonomy-bylines',
        'label' => 'Bylines',
        'width' => '',
        'width_unit' => '%',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => 'taxonomy-bylines',
      ),
      'taxonomy-regions-countries' => 
      array (
        'type' => 'taxonomy-regions-countries',
        'label' => 'Regions & Countries',
        'width' => '',
        'width_unit' => '%',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => 'taxonomy-regions-countries',
      ),
      'taxonomy-research-teams' => 
      array (
        'type' => 'taxonomy-research-teams',
        'label' => 'Research Teams',
        'width' => '',
        'width_unit' => '%',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => 'taxonomy-research-teams',
      ),
      'taxonomy-collection' => 
      array (
        'type' => 'taxonomy-collection',
        'label' => 'Collections',
        'width' => '',
        'width_unit' => '%',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => 'taxonomy-collection',
      ),
      '65675175e56040' => 
      array (
        'type' => 'column-modified',
        'label' => 'Last Modified',
        'width' => '',
        'width_unit' => '%',
        'date_format' => 'F j, Y g:i a',
        'filter' => 'off',
        'filter_label' => '',
        'filter_format' => '',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'off',
        'bulk_edit' => 'off',
        'search' => 'on',
        'name' => '65675175e56040',
      ),
      'c02114a9df3b68' => 
      array (
        'type' => 'column-date_published',
        'label' => 'Date Published',
        'width' => '',
        'width_unit' => '%',
        'date_format' => 'wp_default',
        'filter' => 'off',
        'filter_label' => '',
        'filter_format' => '',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'name' => 'c02114a9df3b68',
      ),
    ),
    'settings' => 
    array (
      'roles' => 
      array (
      ),
      'users' => 
      array (
      ),
      'sorting' => '0',
      'sorting_order' => 'asc',
      'hide_inline_edit' => 'off',
      'hide_bulk_edit' => 'off',
      'hide_bulk_delete' => 'off',
      'hide_smart_filters' => 'off',
      'hide_segments' => 'off',
      'hide_export' => 'off',
      'hide_conditional_formatting' => 'off',
      'hide_new_inline' => 'on',
      'resize_columns' => 'off',
      'column_order' => 'off',
      'hide_filters' => 'off',
      'hide_filter_post_date' => 'off',
      'hide_filter_category' => 'off',
      'hide_filter_yoast_seo_scores' => 'off',
      'hide_filter_yoast_readability_score' => 'off',
      'hide_submenu' => 'off',
      'hide_search' => 'off',
      'hide_bulk_actions' => 'off',
      'hide_row_actions' => 'off',
      'horizontal_scrolling' => 'off',
      'primary_column' => '',
      'filter_segment' => '',
      'wrapping' => 'wrap',
    ),
  ),
);