<?php

return array (
  'version' => '6.2.2',
  'title' => 'Taxonomist',
  'type' => 'post',
  'id' => '64c975ebe04ea',
  'updated' => 1690948430,
  'columns' => 
  array (
    'title' => 
    array (
      'type' => 'title',
      'label' => 'Title',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'name' => 'title',
    ),
    'date' => 
    array (
      'type' => 'date',
      'label' => 'Date',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'sort' => 'on',
      'edit' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'on',
      'filter_label' => '',
      'filter_format' => 'range',
      'name' => 'date',
    ),
    'categories' => 
    array (
      'type' => 'categories',
      'label' => 'Topics',
      'width' => '15',
      'width_unit' => '%',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'on',
      'name' => 'categories',
    ),
    'taxonomy-bylines' => 
    array (
      'type' => 'taxonomy-bylines',
      'label' => 'Bylines',
      'width' => '',
      'width_unit' => '%',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => 'taxonomy-bylines',
    ),
    'taxonomy-regions-countries' => 
    array (
      'type' => 'taxonomy-regions-countries',
      'label' => 'Regions & Countries',
      'width' => '',
      'width_unit' => '%',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'off',
      'filter_label' => '',
      'name' => 'taxonomy-regions-countries',
    ),
    'taxonomy-research-teams' => 
    array (
      'type' => 'taxonomy-research-teams',
      'label' => 'Research Teams',
      'width' => '',
      'width_unit' => '%',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'on',
      'filter_label' => '',
      'name' => 'taxonomy-research-teams',
    ),
    '64c9d344e0c49c' => 
    array (
      'type' => 'taxonomy-formats',
      'label' => 'Formats',
      'width' => '',
      'width_unit' => '%',
      'edit' => 'on',
      'enable_term_creation' => 'off',
      'export' => 'on',
      'sort' => 'on',
      'bulk_edit' => 'on',
      'search' => 'on',
      'filter' => 'on',
      'filter_label' => '',
      'name' => '64c9d344e0c49c',
    ),
    '64c975f1600000' => 
    array (
      'type' => 'column-Parent_Post_Column',
      'label' => 'Parent Post',
      'width' => '',
      'width_unit' => '%',
      'export' => 'on',
      'filter' => 'on',
      'filter_label' => 'All Posts',
      'name' => '64c975f1600000',
    ),
  ),
  'settings' => 
  array (
    'roles' => 
    array (
    ),
    'users' => 
    array (
    ),
    'sorting' => '0',
    'sorting_order' => 'asc',
    'hide_inline_edit' => 'off',
    'hide_bulk_edit' => 'off',
    'hide_bulk_delete' => 'off',
    'hide_smart_filters' => 'off',
    'hide_segments' => 'off',
    'hide_export' => 'off',
    'hide_conditional_formatting' => 'off',
    'hide_new_inline' => 'on',
    'resize_columns' => 'off',
    'column_order' => 'off',
    'hide_filters' => 'off',
    'hide_filter_post_date' => 'off',
    'hide_filter_category' => 'off',
    'hide_filter_post_format' => 'off',
    'hide_filter_yoast_seo_scores' => 'off',
    'hide_filter_yoast_readability_score' => 'off',
    'hide_submenu' => 'off',
    'hide_search' => 'off',
    'hide_bulk_actions' => 'off',
    'hide_row_actions' => 'off',
    'horizontal_scrolling' => 'off',
    'primary_column' => '',
    'filter_segment' => '',
  ),
);