<?php

return array (
  'version' => '6.4.6',
  'list_screen' => 
  array (
    'title' => '',
    'type' => 'block_module',
    'id' => '650b70949a3e3',
    'updated' => 1715177788,
    'columns' => 
    array (
      'title' => 
      array (
        'type' => 'title',
        'label' => 'Title',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'title',
      ),
      'author' => 
      array (
        'type' => 'author',
        'label' => 'Author',
        'width' => '10',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'author',
      ),
      'categories' => 
      array (
        'type' => 'categories',
        'label' => 'Topics',
        'width' => '15',
        'width_unit' => '%',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => 'categories',
      ),
      'taxonomy-block_area' => 
      array (
        'type' => 'taxonomy-block_area',
        'label' => 'Block Areas',
        'width' => '',
        'width_unit' => '%',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => 'taxonomy-block_area',
      ),
      'taxonomy-regions-countries' => 
      array (
        'type' => 'taxonomy-regions-countries',
        'label' => 'Regions & Countries',
        'width' => '',
        'width_unit' => '%',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => 'taxonomy-regions-countries',
      ),
      '433aaec6604188' => 
      array (
        'type' => 'taxonomy-collection',
        'label' => 'Collections',
        'width' => '',
        'width_unit' => '%',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'on',
        'filter_label' => '',
        'name' => '433aaec6604188',
      ),
      'date' => 
      array (
        'type' => 'date',
        'label' => 'Date',
        'width' => '',
        'width_unit' => '%',
        'filter' => 'off',
        'filter_label' => '',
        'filter_format' => '',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'name' => 'date',
      ),
      '1d7b271e6a7efa' => 
      array (
        'type' => 'column-post_gutenberg_blocks',
        'label' => 'Gutenberg Blocks',
        'width' => '',
        'width_unit' => '%',
        'gutenberg_display' => 'count',
        'export' => 'on',
        'name' => '1d7b271e6a7efa',
      ),
    ),
    'settings' => 
    array (
      'roles' => 
      array (
      ),
      'users' => 
      array (
      ),
      'sorting' => '0',
      'sorting_order' => 'asc',
      'hide_inline_edit' => 'off',
      'hide_bulk_edit' => 'off',
      'hide_bulk_delete' => 'off',
      'hide_smart_filters' => 'off',
      'hide_segments' => 'off',
      'hide_export' => 'off',
      'hide_conditional_formatting' => 'off',
      'hide_new_inline' => 'on',
      'resize_columns' => 'off',
      'column_order' => 'off',
      'hide_filters' => 'off',
      'hide_filter_post_date' => 'off',
      'hide_filter_category' => 'off',
      'hide_filter_yoast_seo_scores' => 'on',
      'hide_filter_yoast_readability_score' => 'on',
      'hide_submenu' => 'off',
      'hide_search' => 'off',
      'hide_bulk_actions' => 'off',
      'hide_row_actions' => 'off',
      'horizontal_scrolling' => 'off',
      'primary_column' => '',
      'filter_segment' => '',
      'wrapping' => 'wrap',
    ),
  ),
);