<?php

return array (
  'version' => '6.4.6',
  'list_screen' => 
  array (
    'title' => '',
    'type' => 'page',
    'id' => '661fc3753ef64',
    'updated' => 1713357782,
    'columns' => 
    array (
      'title' => 
      array (
        'type' => 'title',
        'label' => 'Title',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'title',
      ),
      'author' => 
      array (
        'type' => 'author',
        'label' => 'Author',
        'width' => '10',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'author',
      ),
      'taxonomy-collection' => 
      array (
        'type' => 'taxonomy-collection',
        'label' => 'Collections',
        'width' => '',
        'width_unit' => '%',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'taxonomy-collection',
      ),
      'comments' => 
      array (
        'type' => 'comments',
        'label' => '<span class="vers comment-grey-bubble" title="Comments" aria-hidden="true"></span><span class="screen-reader-text">Comments</span>',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'comments',
      ),
      'date' => 
      array (
        'type' => 'date',
        'label' => 'Date',
        'width' => '',
        'width_unit' => '%',
        'filter' => 'off',
        'filter_label' => '',
        'filter_format' => '',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'name' => 'date',
      ),
      '1e1392ba922d0e' => 
      array (
        'type' => 'column-modified',
        'label' => 'Last Modified',
        'width' => '',
        'width_unit' => '%',
        'date_format' => 'F j, Y g:i a',
        'filter' => 'off',
        'filter_label' => '',
        'filter_format' => '',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'name' => '1e1392ba922d0e',
      ),
      'wpseo-score' => 
      array (
        'type' => 'wpseo-score',
        'label' => '<span class="yoast-column-seo-score yoast-column-header-has-tooltip" data-tooltip-text="SEO score"><span class="screen-reader-text">SEO score</span></span></span>',
        'width' => '63',
        'width_unit' => 'px',
        'export' => 'on',
        'sort' => 'on',
        'name' => 'wpseo-score',
      ),
      'wpseo-score-readability' => 
      array (
        'type' => 'wpseo-score-readability',
        'label' => '<span class="yoast-column-readability yoast-column-header-has-tooltip" data-tooltip-text="Readability score"><span class="screen-reader-text">Readability score</span></span></span>',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'name' => 'wpseo-score-readability',
      ),
      'wpseo-title' => 
      array (
        'type' => 'wpseo-title',
        'label' => 'SEO Title',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'wpseo-title',
      ),
      'wpseo-metadesc' => 
      array (
        'type' => 'wpseo-metadesc',
        'label' => 'Meta Desc.',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'wpseo-metadesc',
      ),
      'wpseo-focuskw' => 
      array (
        'type' => 'wpseo-focuskw',
        'label' => 'Keyphrase',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'wpseo-focuskw',
      ),
      'wpseo-links' => 
      array (
        'type' => 'wpseo-links',
        'label' => '<span class="yoast-linked-to yoast-column-header-has-tooltip"><span class="screen-reader-text">Outgoing internal links</span></span>',
        'width' => '',
        'width_unit' => '%',
        'sort' => 'on',
        'name' => 'wpseo-links',
      ),
      'wpseo-cornerstone' => 
      array (
        'type' => 'wpseo-cornerstone',
        'label' => '<span class="yoast-column-cornerstone yoast-column-header-has-tooltip" data-tooltip-text="Is this cornerstone content?"><span class="screen-reader-text">Cornerstone content</span></span>',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'name' => 'wpseo-cornerstone',
      ),
      '1df7ab195f3b64' => 
      array (
        'type' => 'column-last_modified_author',
        'label' => 'Last Modified Author',
        'width' => '',
        'width_unit' => '%',
        'display_author_as' => 'display_name',
        'user_link_to' => 'view_user_posts',
        'export' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => '1df7ab195f3b64',
      ),
    ),
    'settings' => 
    array (
      'roles' => 
      array (
      ),
      'users' => 
      array (
      ),
      'sorting' => '0',
      'sorting_order' => 'asc',
      'hide_inline_edit' => 'off',
      'hide_bulk_edit' => 'off',
      'hide_bulk_delete' => 'off',
      'hide_smart_filters' => 'off',
      'hide_segments' => 'off',
      'hide_export' => 'off',
      'hide_conditional_formatting' => 'off',
      'hide_new_inline' => 'on',
      'resize_columns' => 'off',
      'column_order' => 'off',
      'hide_filters' => 'off',
      'hide_filter_post_date' => 'off',
      'hide_filter_yoast_seo_scores' => 'off',
      'hide_filter_yoast_readability_score' => 'off',
      'hide_submenu' => 'off',
      'hide_search' => 'off',
      'hide_bulk_actions' => 'off',
      'hide_row_actions' => 'off',
      'horizontal_scrolling' => 'off',
      'primary_column' => '',
      'filter_segment' => '',
      'wrapping' => 'wrap',
    ),
  ),
);