<?php

return array (
  'version' => '6.4.10',
  'list_screen' => 
  array (
    'title' => '',
    'type' => 'dataset',
    'id' => '66477056087a4',
    'updated' => 1730128809,
    'columns' => 
    array (
      'title' => 
      array (
        'type' => 'title',
        'label' => 'Title',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'title',
      ),
      '32aeb9c9ca7efa' => 
      array (
        'type' => 'column-slug',
        'label' => 'Slug',
        'width' => '',
        'width_unit' => '%',
        'character_limit' => '',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'off',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => '32aeb9c9ca7efa',
      ),
      'taxonomy-research-teams' => 
      array (
        'type' => 'taxonomy-research-teams',
        'label' => 'Research Teams',
        'width' => '',
        'width_unit' => '%',
        'edit' => 'on',
        'enable_term_creation' => 'off',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'taxonomy-research-teams',
      ),
      'date' => 
      array (
        'type' => 'date',
        'label' => 'Date',
        'width' => '',
        'width_unit' => '%',
        'filter' => 'off',
        'filter_label' => '',
        'filter_format' => '',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'name' => 'date',
      ),
      '5814836bd4fdf4' => 
      array (
        'type' => 'column-meta',
        'label' => 'File',
        'width' => '',
        'width_unit' => '%',
        'field' => '_download_attachment_id',
        'field_type' => 'library_id',
        'image_size' => 'full',
        'image_size_w' => '60',
        'image_size_h' => '60',
        'media_link_to' => 'view',
        'number_of_items' => '10',
        'before' => '',
        'after' => '',
        'edit' => 'on',
        'export' => 'on',
        'sort' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => '5814836bd4fdf4',
      ),
      '54b17e2c828f5c' => 
      array (
        'type' => 'column-postid',
        'label' => 'ID',
        'width' => '100',
        'width_unit' => 'px',
        'before' => '',
        'after' => '',
        'export' => 'on',
        'sort' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => '54b17e2c828f5c',
      ),
      'wpseo-score' => 
      array (
        'type' => 'wpseo-score',
        'label' => '<span class="yoast-column-seo-score yoast-column-header-has-tooltip" data-tooltip-text="SEO score"><span class="screen-reader-text">SEO score</span></span></span>',
        'width' => '63',
        'width_unit' => 'px',
        'export' => 'on',
        'sort' => 'on',
        'name' => 'wpseo-score',
      ),
      'wpseo-score-readability' => 
      array (
        'type' => 'wpseo-score-readability',
        'label' => '<span class="yoast-column-readability yoast-column-header-has-tooltip" data-tooltip-text="Readability score"><span class="screen-reader-text">Readability score</span></span></span>',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'name' => 'wpseo-score-readability',
      ),
      'wpseo-title' => 
      array (
        'type' => 'wpseo-title',
        'label' => 'SEO Title',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'wpseo-title',
      ),
      'wpseo-metadesc' => 
      array (
        'type' => 'wpseo-metadesc',
        'label' => 'Meta Desc.',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'wpseo-metadesc',
      ),
      'wpseo-focuskw' => 
      array (
        'type' => 'wpseo-focuskw',
        'label' => 'Keyphrase',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'wpseo-focuskw',
      ),
    ),
    'settings' => 
    array (
      'roles' => 
      array (
      ),
      'users' => 
      array (
      ),
      'sorting' => '0',
      'sorting_order' => 'asc',
      'hide_inline_edit' => 'off',
      'hide_bulk_edit' => 'off',
      'hide_bulk_delete' => 'off',
      'hide_smart_filters' => 'off',
      'hide_segments' => 'off',
      'hide_export' => 'off',
      'hide_conditional_formatting' => 'off',
      'hide_new_inline' => 'on',
      'resize_columns' => 'off',
      'column_order' => 'off',
      'hide_filters' => 'off',
      'hide_filter_post_date' => 'off',
      'hide_filter_yoast_seo_scores' => 'off',
      'hide_filter_yoast_readability_score' => 'off',
      'hide_submenu' => 'off',
      'hide_search' => 'off',
      'hide_bulk_actions' => 'off',
      'hide_row_actions' => 'off',
      'horizontal_scrolling' => 'off',
      'primary_column' => '',
      'filter_segment' => '',
      'wrapping' => 'wrap',
    ),
  ),
);