import { BaseConfig } from '../types/configTypes';

const baseConfig: BaseConfig = {
	layout: {
		name: 'wp-block-prc-block-chart-builder-controller',
		parentClass: undefined,
		type: 'bar',
		orientation: 'vertical',
		theme: 'light',
		width: 640,
		height: 400,
		padding: { top: 0, bottom: 0, left: 0, right: 0 },
		overflowX: 'responsive',
		horizontalRules: true,
		mobileBreakpoint: 480,
	},
	metadata: {
		active: false,
		title: '',
		subtitle: '',
		note: '',
		source: '',
		tag: 'PEW RESEARCH CENTER',
		alt: '',
	},
	colors: ['#436983', '#bf3927', '#756a7e', '#ea9e2c', '#bc7b2b', '#eeece4'],
	plotBands: {
		active: false,
		allowDrag: false,
		allowResize: false,
		dimension: 'x',
		bands: [],
	},
	independentAxis: {
		active: true,
		label: '',
		scale: 'linear',
		dateFormat: '%-m/%Y',
		domain: [0, 100],
		domainPadding: 20,
		showZero: false,
		padding: 60,
		tickAngle: 0,
		tickCount: 5,
		tickValues: undefined,
		tickFormat: null,
		ticksToLocaleString: false,
		abbreviateTicks: false,
		abbreviateTicksDecimals: 0,
		tickUnit: '', //'%', '$', '€', '£', '¥'
		tickUnitPosition: 'end',
		customTickFormat: null, // function(d) { return d; },
		tickLabels: {
			fontSize: 12,
			padding: 0,
			angle: 0,
			dx: 0,
			dy: 0,
			textAnchor: 'middle',
			verticalAnchor: 'start',
			fill: 'rgba(35, 31, 32,0.7)',
			fontFamily: "'franklin-gothic-urw', Verdana, Geneva, sans-serif",
			maxWidth: 50,
		},
		axisLabel: {
			fontSize: 12,
			fill: 'rgba(35, 31, 32,0.7)',
			padding: 15,
			angle: 0,
			dx: 0,
			dy: 0,
			textAnchor: 'end',
			verticalAnchor: 'middle',
			fontFamily: "'franklin-gothic-urw', Verdana, Geneva, sans-serif",
			maxWidth: 200,
		},
		axis: {
			stroke: 'gray',
			strokeWidth: 1,
		},
		ticks: {
			stroke: 'gray',
			size: 5,
			strokeWidth: 0,
		},
		grid: {
			stroke: '#d3d3d3',
			strokeOpacity: 1,
			strokeWidth: 2,
			strokeDasharray: '.3,6',
		},
	},
	dependentAxis: {
		active: false,
		label: '',
		scale: 'linear',
		padding: 100,
		domain: [0, 200],
		domainPadding: 20,
		showZero: true,
		tickCount: 10,
		tickValues: undefined,
		tickFormat: null,
		ticksToLocaleString: false,
		abbreviateTicks: true,
		abbreviateTicksDecimals: 0,
		tickUnit: '', //'%', '$', '€', '£', '¥'
		tickUnitPosition: 'end',
		customTickFormat: null, // function(d) { return d; },
		tickLabels: {
			fontSize: 12,
			fill: 'rgba(35, 31, 32,0.7)',
			padding: 15,
			angle: 0,
			dx: 0,
			dy: 0,
			textAnchor: 'end',
			verticalAnchor: 'middle',
			fontFamily: "'franklin-gothic-urw', Verdana, Geneva, sans-serif",
			maxWidth: 50,
		},
		axisLabel: {
			fontSize: 12,
			fill: 'rgba(35, 31, 32,0.7)',
			padding: 50,
			angle: 270,
			dx: 0,
			dy: 0,
			textAnchor: 'end',
			verticalAnchor: 'middle',
			fontFamily: "'franklin-gothic-urw', Verdana, Geneva, sans-serif",
			maxWidth: 50,
		},
		ticks: {
			stroke: 'gray',
			size: 5,
			strokeWidth: 0,
		},
		axis: {
			stroke: '#756f6a',
			strokeWidth: 1,
		},
		grid: {
			stroke: '#d3d3d3',
			strokeOpacity: 1,
			strokeWidth: 2,
			strokeDasharray: '.3,6',
		},
	},
	dataRender: {
		x: 'x',
		y: 'y',
		x2: null,
		y2: null,
		sortKey: 'y',
		sortOrder: 'ascending',
		categories: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'],
		xScale: 'linear',
		yScale: 'linear',
		xFormat: null,
		yFormat: null,
		numberFormat: 'en-US',
		isHighlightedColor: '#ECDBAC',
		mapScale: 'threshold',
		mapScaleDomain: [10, 20, 30, 40, 50],
		groupBreaksActive: false,
		groupBreaksCategory: 'Continent',
		groupBreaksCategoryValues: [
			'Africa',
			'Asia',
			'Europe',
			'North America',
			'South America',
			'Oceania',
		],
		groupBreaks: {
			breakStyles: {
				variation: 'empty',
				stroke: '#A4A4A4',
				strokeWidth: 1.4,
				height: 30,
				strokeDasharray: 'none',
			},
			labelStyles: {
				fill: 'black',
				fontStyle: 'normal',
			},
		},
	},
	animate: {
		active: false,
		animationWhitelist: [],
		duration: 2000, //time in ms
	},
	events: {},
	tooltip: {
		active: true,
		activeOnMobile: true,
		headerActive: true,
		headerValue: 'independentValue',
		format: '{{row}}: {{value}}',
		offsetX: 10,
		offsetY: 10,
		abbreviateValue: false,
		absoluteValue: false,
		toFixedDecimal: 0,
		toLocaleString: true,
		customFormat: null, // function(d) { return d; },
		rlsFormat: false,
		dateFormat: '%-m/%Y',
		caretPosition: 'bottom',
		deemphasizeSiblings: false,
		deemphasizeOpacity: 0.5,
		emphasizeStrokeActive: false,
		emphasizeStrokeColor: 'black',
		emphasizeStrokeWidth: 1,
		style: {
			minWidth: 50,
			maxWidth: 150,
			maxHeight: 400,
			minHeight: 20,
			width: '100%',
			height: 'auto',
			fontSize: '13px',
			fontFamily: "'franklin-gothic-urw', Verdana, Geneva, sans-serif",
			background: 'white',
			border: '1px solid black',
			padding: '10px',
			borderRadius: '5px',
			color: 'black',
		},
	},
	legend: {
		active: false,
		orientation: 'row',
		title: '',
		alignment: 'center',
		offsetX: 0,
		offsetY: 0,
		markerStyle: 'rect',
		borderStroke: 'black',
		fill: 'white',
		categories: [],
		labelDelimiter: 'to',
		labelLower: 'Less than ',
		labelUpper: 'More than ',
		fontSize: 12,
		margin: {
			top: 0,
			right: 5,
			bottom: 0,
			left: 0,
		},
	},
	bar: {
		hasRectStroke: false,
		rectStrokeColor: 'white',
		rectStrokeWidth: 1,
		barGroupPadding: 0.2,
		barPadding: 0.2,
	},
	line: {
		interpolation: 'curveLinear',
		strokeDasharray: '1',
		strokeWidth: 3,
		showPoints: false,
		showArea: false,
		areaFillOpacity: 0.4,
	},
	dotPlot: {
		connectPoints: true,
		connectingLine: {
			stroke: '#e6e7e8',
			strokeWidth: 6,
			strokeDasharray: '',
			strokeOpacity: 1,
		},
	},
	errorBars: {
		enabled: false,
		defaultStyles: {
			stroke: '#e6e7e8',
			strokeWidth: 6,
			strokeDasharray: '',
			strokeOpacity: 1,
		},
	},
	explodedBar: {
		columnGap: 16,
	},
	pie: {
		showCategoryLabels: true,
		hasPathStroke: true,
		pathStrokeColor: 'white',
		pathStrokeWidth: 1,
	},
	nodes: {
		pointSize: 3,
		pointFill: 'inherit',
		pointStrokeWidth: 1,
		pointStroke: 'inherit',
		pointCustomSize: null, // function(d) { return d; },
	},
	labels: {
		active: false,
		showFirstLastPointsOnly: false,
		color: 'inherit',
		fontWeight: 200,
		fontSize: 12,
		fontFamily: "'franklin-gothic-urw', Verdana, Geneva, sans-serif",
		labelPositionBar: 'inside',
		labelCutoff: 5,
		labelCutoffMobile: 10,
		labelPositionDX: -25,
		labelPositionDY: 0,
		pieLabelRadius: 60,
		abbreviateValue: false,
		absoluteValue: false,
		toLocaleString: true,
		truncateDecimal: true,
		toFixedDecimal: 0,
		labelUnit: '', //'%', '$', '€', '£', '¥'
		labelUnitPosition: 'end',
		textAnchor: 'middle',
		customLabelFormat: null, // function({datum}) { return datum; },
	},
	voronoi: {
		active: false,
		fill: '#756a7e',
		stroke: '#ccc',
		strokeWidth: 1,
		strokeOpacity: 0.5,
	},
	regression: {
		active: false,
		type: 'linear',
		stroke: '#2a2a2a',
		strokeWidth: 2,
		strokeDasharray: '1',
	},
	divergingBar: {
		positiveCategories: ['y', 'y1'],
		negativeCategories: ['y2', 'y3'],
		netPositiveCategory: 'y4',
		netNegativeCategory: 'y5',
		percentOfInnerWidth: 0.7,
		neutralBar: {
			active: false,
			offsetX: -20,
			separator: true,
			separatorOffsetX: -1,
			category: 'y4',
		},
	},
	diffColumn: {
		active: false,
		category: '',
		columnHeader: 'Diff',
		dx: 0,
		dy: 0,
		style: {
			rectStrokeWidth: 0,
			rectStrokeColor: 'white',
			rectFill: 'none',
			fontWeight: 'normal',
			fontStyle: 'normal',
			fontSize: '10px',
			fontFamily: "'franklin-gothic-urw', Verdana, Geneva, sans-serif",
			headerFontSize: '12px',
			marginLeft: 10,
			width: 30,
			heightOffset: 0,
		},
	},
	map: {
		ignoreSmallStateLabels: false,
		ignoredLabels: [],
		abbreviateLabels: true,
		blockRectSize: 44,
		pathBackgroundFill: '#f7f7f7',
		pathStroke: '#d3d3d3',
		pathStrokeWidth: 0.5,
		showCountyBoundaries: false,
		showStateBoundaries: true,
		zoomActive: false,
		// Projection controls - defaults result in standard world view
		projectionPreset: 'default',
		topologyRegion: 'default', // Which regional topology file to load (independent of projection)
		centerLongitude: 0,
		centerLatitude: 0,
		rotateLambda: 0,
		rotatePhi: 0,
		rotateGamma: 0,
		customScale: 1,
	},
	custom: {
		isCustomChart: false,
		attributes: {
			chartType: null,
		},
	},
	annotations: {
		active: false,
		activeOnMobile: false,
		items: [],
	},
};

export default baseConfig;
